apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vo9wc9vk9-nodejs-gitops
  description: This is GitOps manifest for vo9wc9vk9-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vo9wc9vk9-nodejs
    backstage.io/kubernetes-id: vo9wc9vk9-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vo9wc9vk9-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vo9wc9vk9-nodejs
