apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vo9wc9vk9-nodejs
  janus-idp.io/tekton: vo9wc9vk9-nodejs
  backstage.io/kubernetes-id: vo9wc9vk9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vo9wc9vk9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
