apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vo9wc9vk9-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:5e9da3ef62d2bb5692b9eaaa3400ddd0faceda9b@sha256:dec8778facfd22a5f8f8da754fbcd1d4af522766f1ac060843c06acb3e7e3ff1
          name: container-image
